### ISSUE TITLE
Enforce LGTMs with automated tool

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/project-template#11]
I'm thinking of using PullApprove to enforce the two LGTM sign off

> All decisions are pull requests, and the relevant maintainers make decisions by accepting or refusing the pull request. Review and acceptance by anyone is denoted by adding a comment in the pull request: LGTM. However, only currently listed MAINTAINERS are counted towards the required two LGTMs.

**Comment by caniszczyk** [comment]
Would you be cool with this @crosbymichael ?

If so, I'd love to try it out on the runtime-spec first :)

https://pullapprove.com/

**Comment by cyphar** [comment]
I don't like the fact that it's a proprietary tool. Couldn't we just update Gordon to do it for us (although, I don't have the source code for Gordon either).

**Comment by caniszczyk** [comment]
Things are working properly so we will close this.

@cyphar feel free to write something but the tool seems to be working and GitHub itself is proprietary :)
