### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/project-template#60]
This is listed under "Tier 1: Replace Immediately" in the Inclusive Naming Initiative:
https://inclusivenaming.org/word-lists/tier-1/#master

**Comment by amye** [comment]
<img width="762" alt="Branches_·_opencontainers_project-template" src="https://github.com/opencontainers/project-template/assets/107161/fb200827-403b-445b-92db-9d69bfc2d680">
